spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Fyyf2001
  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8085